local skynet = require "skynet"
skynet.start(function()
    print(skynet.starttime())
    print(skynet.now())

    skynet.timeout(1, function()
        print("in 1", skynet.now())
    end)
    skynet.timeout(2, function()
        print("in 2", skynet.now())
    end)
    skynet.timeout(3, function()
        print("in 3", skynet.now())
    end)

    skynet.timeout(4, function()
        print("in 4", skynet.now())
    end)
    skynet.timeout(100, function()
        print("in 100", skynet.now())
    end)
end)
