local skynet = require "skynet"

skynet.dispatch()

skynet.start(function()
	print("Server start")
	local launcher = skynet.launch("snlua","launcher.lua")
	print("launcher", launcher)
	local console = skynet.launch("snlua","console.lua")
	print("console",console)
	local watchdog = skynet.launch("snlua","watchdog.lua")
	print("watchdog",watchdog)
	local gate = skynet.launch("gate","8888 4 0")
	print("gate",gate)
	local db = skynet.launch("snlua","simpledb.lua")
	print("simpledb",db)
	local connection = skynet.launch("connection","256")
	print("connection",connection)
	local redis = skynet.call(".launcher", "broker .redis snlua redis-cli.lua 127.0.0.1:6379")
	print("redis",redis)
	skynet.exit()
end)